#
# Copyright The Titan Project Contributors.
#

#
# We use release drafter to keep the in-progress release notes up to date:
#
#   https://github.com/marketplace/actions/release-drafter
#
name: Draft Release

on:
  push:
    branches:
      - master
  pull_request:
    types: [opened, reopened, synchronize, edited]

permissions:
  contents: write
  pull-requests: write

jobs:
  update_draft_release:
    runs-on: ubuntu-latest
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}